import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next.js Template with Tailwind CSS and Typescript.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center">
        <h1 className="m-5 text-2xl font-bold">Welcome to Next.js</h1>
        <p className="text-xl">Let&apos;s start coding!</p>
      </main>
    </div>
  );
};

export default Home;
